import { CATEGORIES, type CategorySlug } from '../agent/taxonomy.js'
import type { Dictionary } from './dictionary.js'
import { DEFAULT_PUBLISH_CATEGORIES } from './scope.js'

type Primitive = string | number
type FilterDefinition = { key: string; label: string; type: 'multi-select'; options: Primitive[] }

const compare = (a: Primitive, b: Primitive) => (typeof a === 'number' && typeof b === 'number' ? a - b : String(a) < String(b) ? -1 : String(a) > String(b) ? 1 : 0)

/**
 * Go и Nest трактуют `categories.filterSchema` как allowlist: multi-select без непустого `options` отбрасывается,
 * а в запросе принимаются только перечисленные значения. Поэтому options берутся из закоммиченного словаря
 * (значения, реально существующие у карточек категории); API дополнительно пересекает их с текущим snapshot.
 */
export function filterSchemaFor(dict: Dictionary, slug: CategorySlug): { filters: FilterDefinition[] } {
  const category = CATEGORIES.find((c) => c.slug === slug)
  if (!category) throw new Error(`unknown category ${slug}`)
  const cards = Object.values(dict.canonicals).filter((c) => c.category === slug)
  const filters: FilterDefinition[] = []
  for (const f of category.filters) {
    const values = new Set<Primitive>()
    for (const card of cards) {
      const value = f.key === 'brand' ? card.brand : (card.attributes as Record<string, number | undefined>)[f.key]
      if (value !== null && value !== undefined) values.add(value)
    }
    if (values.size > 0) filters.push({ key: f.key, label: f.label, type: 'multi-select', options: [...values].sort(compare) })
  }
  return { filters }
}

/** Тот же allowlist-контракт, что в Go (`definitions`) и Nest: multi-select без непустого массива примитивов не будет отдан API */
export function assertServableSchema(slug: string, schema: { filters: { key: string; type: string; options?: unknown }[] }): void {
  for (const f of schema.filters) {
    if (f.type !== 'multi-select') continue
    const o = f.options
    if (!Array.isArray(o) || o.length === 0) throw new Error(`${slug}.${f.key}: multi-select without options is dropped by the API`)
    if (!o.every((v) => typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean')) throw new Error(`${slug}.${f.key}: options must be primitives`)
    if (new Set(o).size !== o.length) throw new Error(`${slug}.${f.key}: duplicate options`)
  }
}

const sqlString = (s: string) => `'${s.replaceAll("'", "''")}'`

export function buildTaxonomyMigration(dict: Dictionary): string {
  const rows = DEFAULT_PUBLISH_CATEGORIES.map((slug) => {
    const category = CATEGORIES.find((c) => c.slug === slug)!
    const filterSchema = filterSchemaFor(dict, slug)
    assertServableSchema(slug, filterSchema)
    const schema = JSON.stringify(filterSchema)
    return ` (${sqlString(`cat-${slug}`)},${sqlString(slug)},${sqlString(category.name)},${sqlString(schema)})`
  })
  return [
    '-- Catalog taxonomy for SCRUM-7. Data-only, idempotent, no DDL.',
    '-- GENERATED by `pnpm taxonomy:sql` from data/mapping/dictionary.json; do not edit by hand (pipeline/test/taxonomy.test.ts checks it).',
    '-- Existing rows keep their id; name and filterSchema are set deterministically. Legacy `other` is not touched.',
    'BEGIN;',
    "SET LOCAL lock_timeout = '5s';",
    "SET LOCAL statement_timeout = '30s';",
    '',
    'INSERT INTO public.categories (id, slug, name, "filterSchema") VALUES',
    rows.join(',\n'),
    'ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, "filterSchema" = EXCLUDED."filterSchema";',
    'COMMIT;',
    '',
  ].join('\n')
}
